version: '2.1'

services:
  web:
    environment:
      NODE_ENV: development
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../:/app
      - /app/node_modules
    command: yarn start