defaults: &defaults
  docker:
    - image: circleci/node:9.8.0
  working_directory: ~/wire

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: Install packages
        command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Collect test coverage
          command: yarn coveralls
  deploy:
    <<: *defaults
    environment:
        GOOGLE_PROJECT_ID: bench-projects
        GOOGLE_COMPUTE_ZONE: europe-west1-b
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application artifacts
          command: |
            sudo yarn add webpack-cli webpack@3.8.1
            yarn install
            yarn build
      - run:
          name: Build and deploy
          command: |
            bash ./.circleci/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - staging