defaults: &defaults
  docker:
    - image: circleci/node:9.10.0

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      CC_TEST_REPORTER_ID: 9576c3ea871b02d0acec567f2cdad644ecae01c81c723da4c986ae2dcc81a04c
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
                     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                     chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: yarn test
  deploy:
    <<: *defaults
    environment:
        GOOGLE_PROJECT_ID: bench-projects
        GOOGLE_COMPUTE_ZONE: europe-west1-b
        CC_TEST_REPORTER_ID: 9576c3ea871b02d0acec567f2cdad644ecae01c81c723da4c986ae2dcc81a04c
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application artifacts
          command: |
            sudo yarn add webpack-cli webpack@3.8.1
            yarn install
            yarn build
      - run:
          name: Build and deploy
          command: |
            bash ./.circleci/deploy.sh
    build:
      docker:
        - image: circleci/node:9.10.0

      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Install packages
            command: yarn install
        - run:
            name: Setup Code Climate test-reporter
            command: |
              # download test reporter as a static binary
                       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                       chmod +x ./cc-test-reporter
        - run:
            name: Run tests
            command: yarn test
    deploy:
        docker:
            - image: circleci/node:9.10.0
        environment:
            GOOGLE_PROJECT_ID: bench-projects
            GOOGLE_COMPUTE_ZONE: europe-west1-b
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build application artifacts
                command: |
                    sudo yarn add webpack-cli webpack@3.8.1
                    yarn install
                    yarn build
            - run:
                name: Build and deploy
                command: |
                    chmod +x .circleci/deploy.sh
                    ./.circleci/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - staging
