version: 2
jobs:
    build:
      docker:
        - image: circleci/node:7.10
      steps:
        - checkout
        - run: yarn install
        - run: yarn test
        - run:
            name: Deploy if tests pass
            command: |
              sudo yarn add webpack-cli webpack@3.8.1
              yarn build
        - deploy:
            name: Setup Heroku
            command: |
              bash .circleci/setup-heroku.sh
              chmod 600 ~/.netrc